# Sales Prediction Model using Machine Learning

## Problem Statement
Predict sales based on profit, quantity, and discount.

## Tools Used
- Python
- Pandas
- Scikit-learn

## Approach
- Data cleaning
- Model building (Linear Regression & Random Forest)
- Model evaluation using R2 score

## Results
- Linear Regression Accuracy: ~0.37
- Random Forest Accuracy: ~0.78

## Business Impact
Helps businesses predict future sales and make better decisions.

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel("/content/Superstore.xlsx")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
df = df[['Sales', 'Profit', 'Quantity', 'Discount']]
df.head()

      Sales    Profit  Quantity  Discount
0  261.9600   41.9136         2      0.00
1  731.9400  219.5820         3      0.00
2   14.6200    6.8714         2      0.00
3  957.5775 -383.0310         5      0.45
4   22.3680    2.5164         2      0.20

In [ ]:
X = df[['Profit', 'Quantity', 'Discount']]
y = df['Sales']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
predictions = model.predict(X_test)
predictions[:5]

array([275.69861075, 135.63884085, 183.59912345, 134.6935179 ,
       150.55121434])

In [ ]:
from sklearn.metrics import r2_score

r2_score(y_test, predictions)

0.3710508999461085

In [ ]:
from sklearn.ensemble import RandomForestRegressor

model2 = RandomForestRegressor()
model2.fit(X_train, y_train)

pred2 = model2.predict(X_test)

from sklearn.metrics import r2_score
r2_score(y_test, pred2)

0.7834989054031161